//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartLMS.Domain.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SmartLMS.Domain.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string AboutMenuItem {
            get {
                return ResourceManager.GetString("AboutMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Through the research of Multi-instrumentalist, Composer and Arranger Mario Aphonso III with the music of the world, a musical journey begins that connects strands and cultures through modal music from the Middle East, Turkey, Mediterranean and Balkans, to the Arab world and music Brazilian instrumental. Within the study of theory, the practice of traditional repertoire and language are fundamental to a rich and complete experience. The need to share this research with musicians and friends has become a very [rest of string was truncated]&quot;;.
        /// </summary>
        public static string AboutText {
            get {
                return ResourceManager.GetString("AboutText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Your Company Training.
        /// </summary>
        public static string AboutTitle {
            get {
                return ResourceManager.GetString("AboutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access History.
        /// </summary>
        public static string AccessHistoryMenuItem {
            get {
                return ResourceManager.GetString("AccessHistoryMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access History.
        /// </summary>
        public static string AccessHistoryPageTitle {
            get {
                return ResourceManager.GetString("AccessHistoryPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string AccessTypeAll {
            get {
                return ResourceManager.GetString("AccessTypeAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class.
        /// </summary>
        public static string AccessTypeClass {
            get {
                return ResourceManager.GetString("AccessTypeClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access Type.
        /// </summary>
        public static string AccessTypeLabel {
            get {
                return ResourceManager.GetString("AccessTypeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support Material.
        /// </summary>
        public static string AccessTypeSupportMaterial {
            get {
                return ResourceManager.GetString("AccessTypeSupportMaterial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string ActiveFieldName {
            get {
                return ResourceManager.GetString("ActiveFieldName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to type the term you want to find.
        /// </summary>
        public static string AdminSearchText {
            get {
                return ResourceManager.GetString("AdminSearchText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is another user to this login.
        /// </summary>
        public static string AnotherUserToThisLoginException {
            get {
                return ResourceManager.GetString("AnotherUserToThisLoginException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authenticating.
        /// </summary>
        public static string Authenticating {
            get {
                return ResourceManager.GetString("Authenticating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to available.
        /// </summary>
        public static string Available {
            get {
                return ResourceManager.GetString("Available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string BackButton {
            get {
                return ResourceManager.GetString("BackButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to Home.
        /// </summary>
        public static string BackToHome {
            get {
                return ResourceManager.GetString("BackToHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to index.
        /// </summary>
        public static string BackToIndex {
            get {
                return ResourceManager.GetString("BackToIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to login.
        /// </summary>
        public static string BackToLogin {
            get {
                return ResourceManager.GetString("BackToLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string CancelFileButton {
            get {
                return ResourceManager.GetString("CancelFileButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string CancelImageButton {
            get {
                return ResourceManager.GetString("CancelImageButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Language.
        /// </summary>
        public static string ChangeLanguageMenuItem {
            get {
                return ResourceManager.GetString("ChangeLanguageMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill in the form below to change your password.
        /// </summary>
        public static string ChangePasswordInformation {
            get {
                return ResourceManager.GetString("ChangePasswordInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change password.
        /// </summary>
        public static string ChangePasswordMenuItem {
            get {
                return ResourceManager.GetString("ChangePasswordMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        public static string ChangePasswordPageTitle {
            get {
                return ResourceManager.GetString("ChangePasswordPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to and check below the courses by subject.
        /// </summary>
        public static string CheckCoursesBySubjectMessage {
            get {
                return ResourceManager.GetString("CheckCoursesBySubjectMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class created.
        /// </summary>
        public static string ClassCreatedToastrMessage {
            get {
                return ResourceManager.GetString("ClassCreatedToastrMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class deleted!.
        /// </summary>
        public static string ClassDeletedToastrMessage {
            get {
                return ResourceManager.GetString("ClassDeletedToastrMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class Index.
        /// </summary>
        public static string ClassIndex {
            get {
                return ResourceManager.GetString("ClassIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class Management.
        /// </summary>
        public static string ClassManagementPageTitle {
            get {
                return ResourceManager.GetString("ClassManagementPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class.
        /// </summary>
        public static string ClassName {
            get {
                return ResourceManager.GetString("ClassName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string ClassNameFieldName {
            get {
                return ResourceManager.GetString("ClassNameFieldName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classes.
        /// </summary>
        public static string ClassPlural {
            get {
                return ResourceManager.GetString("ClassPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classrooms.
        /// </summary>
        public static string ClassroomAdminMenuItem {
            get {
                return ResourceManager.GetString("ClassroomAdminMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classroom deleted!.
        /// </summary>
        public static string ClassroomDeletedToastrMessage {
            get {
                return ResourceManager.GetString("ClassroomDeletedToastrMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classroom management.
        /// </summary>
        public static string ClassroomManagementPageTitle {
            get {
                return ResourceManager.GetString("ClassroomManagementPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classroom management.
        /// </summary>
        public static string ClassroomManagementToastrTitle {
            get {
                return ResourceManager.GetString("ClassroomManagementToastrTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classroom.
        /// </summary>
        public static string ClassroomName {
            get {
                return ResourceManager.GetString("ClassroomName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string ClassroomNameFieldName {
            get {
                return ResourceManager.GetString("ClassroomNameFieldName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classrooms.
        /// </summary>
        public static string ClassroomPlural {
            get {
                return ResourceManager.GetString("ClassroomPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classroom required.
        /// </summary>
        public static string ClassroomRequired {
            get {
                return ResourceManager.GetString("ClassroomRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classroom.
        /// </summary>
        public static string ClassroomsMenuItem {
            get {
                return ResourceManager.GetString("ClassroomsMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classroom updated.
        /// </summary>
        public static string ClassroomUpdatedToastrMessage {
            get {
                return ResourceManager.GetString("ClassroomUpdatedToastrMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classroom Update.
        /// </summary>
        public static string ClassroomUpdatePageTitle {
            get {
                return ResourceManager.GetString("ClassroomUpdatePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class Update.
        /// </summary>
        public static string ClassUpdatePageTitle {
            get {
                return ResourceManager.GetString("ClassUpdatePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string CloseButton {
            get {
                return ResourceManager.GetString("CloseButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make your comment about the class here.
        /// </summary>
        public static string CommentPlaceholder {
            get {
                return ResourceManager.GetString("CommentPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type your comment.
        /// </summary>
        public static string CommentRequired {
            get {
                return ResourceManager.GetString("CommentRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discussion.
        /// </summary>
        public static string CommentsTitle {
            get {
                return ResourceManager.GetString("CommentsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Concluded.
        /// </summary>
        public static string ConcludedLabel {
            get {
                return ResourceManager.GetString("ConcludedLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm your password.
        /// </summary>
        public static string ConfirmPasswordLabel {
            get {
                return ResourceManager.GetString("ConfirmPasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content.
        /// </summary>
        public static string Content {
            get {
                return ResourceManager.GetString("Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content management.
        /// </summary>
        public static string ContentManagementSection {
            get {
                return ResourceManager.GetString("ContentManagementSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content management.
        /// </summary>
        public static string ContentManagementToastrTitle {
            get {
                return ResourceManager.GetString("ContentManagementToastrTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class type.
        /// </summary>
        public static string ContentTypeName {
            get {
                return ResourceManager.GetString("ContentTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Course created.
        /// </summary>
        public static string CourseCreatedToastrMessage {
            get {
                return ResourceManager.GetString("CourseCreatedToastrMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Course deleted!.
        /// </summary>
        public static string CourseDeletedToastrMessage {
            get {
                return ResourceManager.GetString("CourseDeletedToastrMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Course Index.
        /// </summary>
        public static string CourseIndex {
            get {
                return ResourceManager.GetString("CourseIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Course Management.
        /// </summary>
        public static string CourseManagementPageTitle {
            get {
                return ResourceManager.GetString("CourseManagementPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Course.
        /// </summary>
        public static string CourseName {
            get {
                return ResourceManager.GetString("CourseName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string CourseNameFieldName {
            get {
                return ResourceManager.GetString("CourseNameFieldName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This course is not available at this moment.
        /// </summary>
        public static string CourseNotAvailableToastrMessage {
            get {
                return ResourceManager.GetString("CourseNotAvailableToastrMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Courses.
        /// </summary>
        public static string CoursePlural {
            get {
                return ResourceManager.GetString("CoursePlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Included courses in the classroom.
        /// </summary>
        public static string CoursesInClassroomTitle {
            get {
                return ResourceManager.GetString("CoursesInClassroomTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Course updated.
        /// </summary>
        public static string CourseUpdatedToastrMessage {
            get {
                return ResourceManager.GetString("CourseUpdatedToastrMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Course Update.
        /// </summary>
        public static string CourseUpdateTitle {
            get {
                return ResourceManager.GetString("CourseUpdateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new Class.
        /// </summary>
        public static string CreateClassPageTitle {
            get {
                return ResourceManager.GetString("CreateClassPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new Classroom.
        /// </summary>
        public static string CreateClassroomPageTitle {
            get {
                return ResourceManager.GetString("CreateClassroomPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new course.
        /// </summary>
        public static string CreateCoursePageTitle {
            get {
                return ResourceManager.GetString("CreateCoursePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created at.
        /// </summary>
        public static string CreatedAtFieldName {
            get {
                return ResourceManager.GetString("CreatedAtFieldName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new Knowledge Area.
        /// </summary>
        public static string CreateKnowledgeAreaPageTitle {
            get {
                return ResourceManager.GetString("CreateKnowledgeAreaPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new student.
        /// </summary>
        public static string CreateStudentPageTitle {
            get {
                return ResourceManager.GetString("CreateStudentPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new subject.
        /// </summary>
        public static string CreateSubjectPageTitle {
            get {
                return ResourceManager.GetString("CreateSubjectPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new teacher.
        /// </summary>
        public static string CreateTeacherPageTitle {
            get {
                return ResourceManager.GetString("CreateTeacherPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div&gt;
        ///Hi {username}, your Your Company Training credendials are:
        ///&lt;/div&gt;
        ///&lt;div&gt;Login: {login}&lt;/div&gt;&lt;div&gt;Password: {password}.&lt;/div&gt;
        ///&lt;div&gt;Access the platform by the following link &lt;a href=&apos;{link}&apos;&gt;here&lt;/a&gt;.&lt;/div&gt;
        ///&lt;div&gt;Regards, Your Company Training Team&lt;/div&gt;.
        /// </summary>
        public static string CreatingUserNotificationEmailBody {
            get {
                return ResourceManager.GetString("CreatingUserNotificationEmailBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to Your Company Training.
        /// </summary>
        public static string CreatingUserNotificationEmailSubject {
            get {
                return ResourceManager.GetString("CreatingUserNotificationEmailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Days to deliver.
        /// </summary>
        public static string DaysToDeliverLabel {
            get {
                return ResourceManager.GetString("DaysToDeliverLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to delete the class.
        /// </summary>
        public static string DeleteClassConfirmationText {
            get {
                return ResourceManager.GetString("DeleteClassConfirmationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Class.
        /// </summary>
        public static string DeleteClassConfirmationTitle {
            get {
                return ResourceManager.GetString("DeleteClassConfirmationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to delete the classroom.
        /// </summary>
        public static string DeleteClassroomConfirmationText {
            get {
                return ResourceManager.GetString("DeleteClassroomConfirmationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Classroom.
        /// </summary>
        public static string DeleteClassroomConfirmationTitle {
            get {
                return ResourceManager.GetString("DeleteClassroomConfirmationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to delete the course.
        /// </summary>
        public static string DeleteCourseConfirmationText {
            get {
                return ResourceManager.GetString("DeleteCourseConfirmationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete course.
        /// </summary>
        public static string DeleteCourseConfirmationTitle {
            get {
                return ResourceManager.GetString("DeleteCourseConfirmationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string DeleteFileButton {
            get {
                return ResourceManager.GetString("DeleteFileButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string DeleteImageButton {
            get {
                return ResourceManager.GetString("DeleteImageButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to delete the knowledge area.
        /// </summary>
        public static string DeleteKnowledgeAreaConfirmationText {
            get {
                return ResourceManager.GetString("DeleteKnowledgeAreaConfirmationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Knowledge Area.
        /// </summary>
        public static string DeleteKnowledgeAreaConfirmationTitle {
            get {
                return ResourceManager.GetString("DeleteKnowledgeAreaConfirmationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to delete the student.
        /// </summary>
        public static string DeleteStudentConfirmationText {
            get {
                return ResourceManager.GetString("DeleteStudentConfirmationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Student.
        /// </summary>
        public static string DeleteStudentConfirmationTitle {
            get {
                return ResourceManager.GetString("DeleteStudentConfirmationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to delete the subject.
        /// </summary>
        public static string DeleteSubjectConfirmationText {
            get {
                return ResourceManager.GetString("DeleteSubjectConfirmationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to delete the teacher.
        /// </summary>
        public static string DeleteTeacherConfirmationText {
            get {
                return ResourceManager.GetString("DeleteTeacherConfirmationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Teacher.
        /// </summary>
        public static string DeleteTeacherConfirmationTitle {
            get {
                return ResourceManager.GetString("DeleteTeacherConfirmationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hi {username}, how are you? &lt;br /&gt; The class &lt;a href=&apos;{link}/Class/Watch/{classId}&apos;&gt;{classname}&lt;/a&gt; is now avaialble on the course &lt;a href=&apos;{link}/Class/Index/{courseId}&apos;&gt;{coursename}&lt;/a&gt; &lt;br /&gt;Have a productive study! &lt;br /&gt;&lt;br /&gt; Your Company Training Team.
        /// </summary>
        public static string DeliveredClassNotificationEmailBody {
            get {
                return ResourceManager.GetString("DeliveredClassNotificationEmailBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Company Training - New available class.
        /// </summary>
        public static string DeliveredClassNotificationEmailSubject {
            get {
                return ResourceManager.GetString("DeliveredClassNotificationEmailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery date.
        /// </summary>
        public static string DeliveryPlanDate {
            get {
                return ResourceManager.GetString("DeliveryPlanDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery Plan History.
        /// </summary>
        public static string DeliveryPlanHistory {
            get {
                return ResourceManager.GetString("DeliveryPlanHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery Plan.
        /// </summary>
        public static string DeliveryPlanName {
            get {
                return ResourceManager.GetString("DeliveryPlanName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery Plan.
        /// </summary>
        public static string DeliveryPlanPageTitle {
            get {
                return ResourceManager.GetString("DeliveryPlanPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery Plans.
        /// </summary>
        public static string DeliveryPlanPlural {
            get {
                return ResourceManager.GetString("DeliveryPlanPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string DetailsColumn {
            get {
                return ResourceManager.GetString("DetailsColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drag and drop the documents here or just click to select them.
        /// </summary>
        public static string DragAndDropFileMessage {
            get {
                return ResourceManager.GetString("DragAndDropFileMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drag and drop the course image here or just click to select it.
        /// </summary>
        public static string DragAndDropImageMessage {
            get {
                return ResourceManager.GetString("DragAndDropImageMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit/Delete.
        /// </summary>
        public static string EditDeleteColumn {
            get {
                return ResourceManager.GetString("EditDeleteColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail not found.
        /// </summary>
        public static string EmailNotFound {
            get {
                return ResourceManager.GetString("EmailNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email required.
        /// </summary>
        public static string EmailRequired {
            get {
                return ResourceManager.GetString("EmailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End date.
        /// </summary>
        public static string EndDateLabel {
            get {
                return ResourceManager.GetString("EndDateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Details.
        /// </summary>
        public static string ErrorDetailsTitle {
            get {
                return ResourceManager.GetString("ErrorDetailsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error saving image.
        /// </summary>
        public static string ErrorSavingImage {
            get {
                return ResourceManager.GetString("ErrorSavingImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support Material.
        /// </summary>
        public static string FileName {
            get {
                return ResourceManager.GetString("FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support materials.
        /// </summary>
        public static string FilePlural {
            get {
                return ResourceManager.GetString("FilePlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        public static string FilterButton {
            get {
                return ResourceManager.GetString("FilterButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot your password?.
        /// </summary>
        public static string ForgotPasswordButton {
            get {
                return ResourceManager.GetString("ForgotPasswordButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type your subscribed email.
        /// </summary>
        public static string ForgotPasswordLoginLabel {
            get {
                return ResourceManager.GetString("ForgotPasswordLoginLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We sent an e-mail to you with your password..
        /// </summary>
        public static string ForgotPasswordMessage {
            get {
                return ResourceManager.GetString("ForgotPasswordMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot your password?.
        /// </summary>
        public static string ForgotPasswordTitle {
            get {
                return ResourceManager.GetString("ForgotPasswordTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        public static string ImageFieldName {
            get {
                return ResourceManager.GetString("ImageFieldName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login must be a valid email.
        /// </summary>
        public static string InvalidLogin {
            get {
                return ResourceManager.GetString("InvalidLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid User or password.
        /// </summary>
        public static string InvalidUserOrPassword {
            get {
                return ResourceManager.GetString("InvalidUserOrPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Knowledge area deleted!.
        /// </summary>
        public static string KnowledgeAreaDeletedToastrMessage {
            get {
                return ResourceManager.GetString("KnowledgeAreaDeletedToastrMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Knowledge Area Index.
        /// </summary>
        public static string KnowledgeAreaIndex {
            get {
                return ResourceManager.GetString("KnowledgeAreaIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Knowledge Area Management.
        /// </summary>
        public static string KnowledgeAreaManagementPageTitle {
            get {
                return ResourceManager.GetString("KnowledgeAreaManagementPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Knowledge Area.
        /// </summary>
        public static string KnowledgeAreaName {
            get {
                return ResourceManager.GetString("KnowledgeAreaName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string KnowledgeAreaNameFieldName {
            get {
                return ResourceManager.GetString("KnowledgeAreaNameFieldName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Knowledge Areas.
        /// </summary>
        public static string KnowledgeAreaPlural {
            get {
                return ResourceManager.GetString("KnowledgeAreaPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Knowledge Area Update.
        /// </summary>
        public static string KnowledgeAreaUpdatePageTitle {
            get {
                return ResourceManager.GetString("KnowledgeAreaUpdatePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New classes.
        /// </summary>
        public static string LastClassesTitle {
            get {
                return ResourceManager.GetString("LastClassesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type your email.
        /// </summary>
        public static string LoginEmailLabel {
            get {
                return ResourceManager.GetString("LoginEmailLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type your password.
        /// </summary>
        public static string LoginPasswordLabel {
            get {
                return ResourceManager.GetString("LoginPasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login required.
        /// </summary>
        public static string LoginRequired {
            get {
                return ResourceManager.GetString("LoginRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log out.
        /// </summary>
        public static string LogoutMenuItem {
            get {
                return ResourceManager.GetString("LogoutMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to by.
        /// </summary>
        public static string MadeBy {
            get {
                return ResourceManager.GetString("MadeBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Made with.
        /// </summary>
        public static string MadeWithLoveMessage {
            get {
                return ResourceManager.GetString("MadeWithLoveMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Management.
        /// </summary>
        public static string ManagementAdminMenuItem {
            get {
                return ResourceManager.GetString("ManagementAdminMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Have been found &lt;strong&gt;{{pageCount}}&lt;/strong&gt; pages for the term &lt;strong&gt;&quot;{{term}}&quot;&lt;/strong&gt;.
        /// </summary>
        public static string ManyPagesResultMessage {
            get {
                return ResourceManager.GetString("ManyPagesResultMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type your message.
        /// </summary>
        public static string MessageRequired {
            get {
                return ResourceManager.GetString("MessageRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monitoring.
        /// </summary>
        public static string MonitoringMenuSectionMenuDivider {
            get {
                return ResourceManager.GetString("MonitoringMenuSectionMenuDivider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Courses.
        /// </summary>
        public static string MyCoursesTitle {
            get {
                return ResourceManager.GetString("MyCoursesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type your new password.
        /// </summary>
        public static string NewPasswordLabel {
            get {
                return ResourceManager.GetString("NewPasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next classes.
        /// </summary>
        public static string NextClasses {
            get {
                return ResourceManager.GetString("NextClasses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to next &amp;gt;.
        /// </summary>
        public static string NextPage {
            get {
                return ResourceManager.GetString("NextPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have access to this class.
        /// </summary>
        public static string NoAccessToClassMessage {
            get {
                return ResourceManager.GetString("NoAccessToClassMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No class found.
        /// </summary>
        public static string NoClassAdmin {
            get {
                return ResourceManager.GetString("NoClassAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No classes in this section.
        /// </summary>
        public static string NoClasses {
            get {
                return ResourceManager.GetString("NoClasses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Classrooms found.
        /// </summary>
        public static string NoClassroomAdmin {
            get {
                return ResourceManager.GetString("NoClassroomAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We don&apos;t have any content in this section yet.
        /// </summary>
        public static string NoCourses {
            get {
                return ResourceManager.GetString("NoCourses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Courses found.
        /// </summary>
        public static string NoCoursesAdmin {
            get {
                return ResourceManager.GetString("NoCoursesAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Knowledge Areas found.
        /// </summary>
        public static string NoKnowledgeAreasAdmin {
            get {
                return ResourceManager.GetString("NoKnowledgeAreasAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No more comments to this class..
        /// </summary>
        public static string NoMoreComments {
            get {
                return ResourceManager.GetString("NoMoreComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have notices at this moment.
        /// </summary>
        public static string NoNotices {
            get {
                return ResourceManager.GetString("NoNotices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your search did not return any results for the term &lt;strong&gt;&quot;{{term}}&quot;&lt;/strong&gt;.
        /// </summary>
        public static string NoSearchResultsMessage {
            get {
                return ResourceManager.GetString("NoSearchResultsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Students found.
        /// </summary>
        public static string NoStudentsAdmin {
            get {
                return ResourceManager.GetString("NoStudentsAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Subjects found.
        /// </summary>
        public static string NoSubjectsAdmin {
            get {
                return ResourceManager.GetString("NoSubjectsAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not allowed to watch this class.
        /// </summary>
        public static string NotAllowedWatchClassToastrMessage {
            get {
                return ResourceManager.GetString("NotAllowedWatchClassToastrMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Teachers found.
        /// </summary>
        public static string NoTeachers {
            get {
                return ResourceManager.GetString("NoTeachers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notice History.
        /// </summary>
        public static string NoticeHistoryPageTitle {
            get {
                return ResourceManager.GetString("NoticeHistoryPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notices.
        /// </summary>
        public static string NoticeMenuItem {
            get {
                return ResourceManager.GetString("NoticeMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        public static string NoticeMessageLabel {
            get {
                return ResourceManager.GetString("NoticeMessageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type your message here.
        /// </summary>
        public static string NoticeMessagePlaceholder {
            get {
                return ResourceManager.GetString("NoticeMessagePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notices.
        /// </summary>
        public static string NoticesPanelTitle {
            get {
                return ResourceManager.GetString("NoticesPanelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string NoticeTypeAll {
            get {
                return ResourceManager.GetString("NoticeTypeAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classroom.
        /// </summary>
        public static string NoticeTypeClassroom {
            get {
                return ResourceManager.GetString("NoticeTypeClassroom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notice Type.
        /// </summary>
        public static string NoticeTypeLabel {
            get {
                return ResourceManager.GetString("NoticeTypeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal.
        /// </summary>
        public static string NoticeTypePersonal {
            get {
                return ResourceManager.GetString("NoticeTypePersonal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Public.
        /// </summary>
        public static string NoticeTypePublic {
            get {
                return ResourceManager.GetString("NoticeTypePublic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification.
        /// </summary>
        public static string NotificationToastrTitle {
            get {
                return ResourceManager.GetString("NotificationToastrTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Has been found &lt;strong&gt;one&lt;/strong&gt; page for the term &lt;strong&gt;&quot;{{term}}&quot;&lt;/strong&gt;.
        /// </summary>
        public static string OnePageResultMessage {
            get {
                return ResourceManager.GetString("OnePageResultMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The course can have only one image.
        /// </summary>
        public static string OnlyOneImageCourseMessage {
            get {
                return ResourceManager.GetString("OnlyOneImageCourseMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order.
        /// </summary>
        public static string OrderFieldName {
            get {
                return ResourceManager.GetString("OrderFieldName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        public static string PasswordConfirmationFieldName {
            get {
                return ResourceManager.GetString("PasswordConfirmationFieldName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password confirmation required.
        /// </summary>
        public static string PasswordConfirmationRequired {
            get {
                return ResourceManager.GetString("PasswordConfirmationRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password doesn&apos;t match.
        /// </summary>
        public static string PasswordDoenstMatch {
            get {
                return ResourceManager.GetString("PasswordDoenstMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string PasswordFieldName {
            get {
                return ResourceManager.GetString("PasswordFieldName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div&gt;Hi {username}, your Your Company Training credendials are:&lt;/div&gt;
        ///&lt;div&gt;
        ///Login: {login}.
        ///&lt;/div&gt;
        ///&lt;div&gt;
        ///Password: {password}
        ///&lt;/div&gt;
        ///&lt;div&gt;
        ///Access the platform by the following link &lt;a href=&apos;{link}&apos;&gt;here&lt;/a&gt;.
        ///&lt;/div&gt;
        ///&lt;div&gt;
        ///Regards, Your Company Training Team
        ///&lt;/div&gt;.
        /// </summary>
        public static string PasswordRecoveryEmailBody {
            get {
                return ResourceManager.GetString("PasswordRecoveryEmailBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Company Training - Password Recovery.
        /// </summary>
        public static string PasswordRecoveryEmailSubject {
            get {
                return ResourceManager.GetString("PasswordRecoveryEmailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password has been updated.
        /// </summary>
        public static string PasswordUpdatedNoticeMessage {
            get {
                return ResourceManager.GetString("PasswordUpdatedNoticeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password updated!.
        /// </summary>
        public static string PasswordUpdatedToastrMessage {
            get {
                return ResourceManager.GetString("PasswordUpdatedToastrMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to People management.
        /// </summary>
        public static string PeopleManagementSection {
            get {
                return ResourceManager.GetString("PeopleManagementSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to from.
        /// </summary>
        public static string PersonalInfoUpdatedFrom {
            get {
                return ResourceManager.GetString("PersonalInfoUpdatedFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal info updated.
        /// </summary>
        public static string PersonalInfoUpdatedTitle {
            get {
                return ResourceManager.GetString("PersonalInfoUpdatedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to.
        /// </summary>
        public static string PersonalInfoUpdatedTo {
            get {
                return ResourceManager.GetString("PersonalInfoUpdatedTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal.
        /// </summary>
        public static string PersonalName {
            get {
                return ResourceManager.GetString("PersonalName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;lt; previous.
        /// </summary>
        public static string PreviousPage {
            get {
                return ResourceManager.GetString("PreviousPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Public.
        /// </summary>
        public static string PublicName {
            get {
                return ResourceManager.GetString("PublicName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query filters.
        /// </summary>
        public static string QueryFiltersTitle {
            get {
                return ResourceManager.GetString("QueryFiltersTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stay on top of the news through the quick access panels.
        /// </summary>
        public static string QuickPanelsMessage {
            get {
                return ResourceManager.GetString("QuickPanelsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember Me.
        /// </summary>
        public static string RememberMeLabel {
            get {
                return ResourceManager.GetString("RememberMeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What do you want to learn?.
        /// </summary>
        public static string SearchBarText {
            get {
                return ResourceManager.GetString("SearchBarText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string SearchButton {
            get {
                return ResourceManager.GetString("SearchButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search by.
        /// </summary>
        public static string SearchByLabel {
            get {
                return ResourceManager.GetString("SearchByLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See the full index.
        /// </summary>
        public static string SeeFullIndex {
            get {
                return ResourceManager.GetString("SeeFullIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See also other classes for this course.
        /// </summary>
        public static string SeeOtherClasses {
            get {
                return ResourceManager.GetString("SeeOtherClasses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See also other courses for this subject.
        /// </summary>
        public static string SeeOtherCourses {
            get {
                return ResourceManager.GetString("SeeOtherCourses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See also other knowledge areas.
        /// </summary>
        public static string SeeOtherKnowledgeAreas {
            get {
                return ResourceManager.GetString("SeeOtherKnowledgeAreas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See also other subjects for this knowledge area.
        /// </summary>
        public static string SeeOtherSubjects {
            get {
                return ResourceManager.GetString("SeeOtherSubjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a class.
        /// </summary>
        public static string SelectClass {
            get {
                return ResourceManager.GetString("SelectClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a Classroom.
        /// </summary>
        public static string SelectClassroom {
            get {
                return ResourceManager.GetString("SelectClassroom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a content type.
        /// </summary>
        public static string SelectContentType {
            get {
                return ResourceManager.GetString("SelectContentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a course.
        /// </summary>
        public static string SelectCourse {
            get {
                return ResourceManager.GetString("SelectCourse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a knowledge area.
        /// </summary>
        public static string SelectKnowledgeArea {
            get {
                return ResourceManager.GetString("SelectKnowledgeArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select below one of the classes available in this course.
        /// </summary>
        public static string SelectOneCourseIndexMessage {
            get {
                return ResourceManager.GetString("SelectOneCourseIndexMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select below one of the courses available in this subject.
        /// </summary>
        public static string SelectOneSubjectIndexMessage {
            get {
                return ResourceManager.GetString("SelectOneSubjectIndexMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a Student.
        /// </summary>
        public static string SelectStudent {
            get {
                return ResourceManager.GetString("SelectStudent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a subject.
        /// </summary>
        public static string SelectSubject {
            get {
                return ResourceManager.GetString("SelectSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a teacher.
        /// </summary>
        public static string SelectTeacher {
            get {
                return ResourceManager.GetString("SelectTeacher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        public static string SendButton {
            get {
                return ResourceManager.GetString("SendButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending.
        /// </summary>
        public static string Sending {
            get {
                return ResourceManager.GetString("Sending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send notices visible to all users by this form.
        /// </summary>
        public static string SendNoticeInformation {
            get {
                return ResourceManager.GetString("SendNoticeInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Notice.
        /// </summary>
        public static string SendNoticeMenuItem {
            get {
                return ResourceManager.GetString("SendNoticeMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Public Notices.
        /// </summary>
        public static string SendNoticePageTitle {
            get {
                return ResourceManager.GetString("SendNoticePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start date.
        /// </summary>
        public static string StartDateLabel {
            get {
                return ResourceManager.GetString("StartDateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student access.
        /// </summary>
        public static string StudentAccessMenuItem {
            get {
                return ResourceManager.GetString("StudentAccessMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Students.
        /// </summary>
        public static string StudentAdminMenuItem {
            get {
                return ResourceManager.GetString("StudentAdminMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student deleted!.
        /// </summary>
        public static string StudentDeletedToastrMessage {
            get {
                return ResourceManager.GetString("StudentDeletedToastrMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string StudentEmailFieldName {
            get {
                return ResourceManager.GetString("StudentEmailFieldName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student Management.
        /// </summary>
        public static string StudentManagementPageTitle {
            get {
                return ResourceManager.GetString("StudentManagementPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student Management.
        /// </summary>
        public static string StudentManagementToastrTitle {
            get {
                return ResourceManager.GetString("StudentManagementToastrTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student.
        /// </summary>
        public static string StudentName {
            get {
                return ResourceManager.GetString("StudentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string StudentNameFieldName {
            get {
                return ResourceManager.GetString("StudentNameFieldName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Students.
        /// </summary>
        public static string StudentPlural {
            get {
                return ResourceManager.GetString("StudentPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Students subscribed in the classroom.
        /// </summary>
        public static string StudentsInClassroomTitle {
            get {
                return ResourceManager.GetString("StudentsInClassroomTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student Update.
        /// </summary>
        public static string StudentUpdatePageTitle {
            get {
                return ResourceManager.GetString("StudentUpdatePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject deleted!.
        /// </summary>
        public static string SubjectDeletedToastrMessage {
            get {
                return ResourceManager.GetString("SubjectDeletedToastrMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject Index.
        /// </summary>
        public static string SubjectIndex {
            get {
                return ResourceManager.GetString("SubjectIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject Management.
        /// </summary>
        public static string SubjectManagementPageTitle {
            get {
                return ResourceManager.GetString("SubjectManagementPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject.
        /// </summary>
        public static string SubjectName {
            get {
                return ResourceManager.GetString("SubjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string SubjectNameFieldName {
            get {
                return ResourceManager.GetString("SubjectNameFieldName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This subject is not available at this moment.
        /// </summary>
        public static string SubjectNotAvailableToastrMessage {
            get {
                return ResourceManager.GetString("SubjectNotAvailableToastrMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subjects.
        /// </summary>
        public static string SubjectPlural {
            get {
                return ResourceManager.GetString("SubjectPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject Update.
        /// </summary>
        public static string SubjectUpdatePageTitle {
            get {
                return ResourceManager.GetString("SubjectUpdatePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscribed at.
        /// </summary>
        public static string SubscribedAtColumn {
            get {
                return ResourceManager.GetString("SubscribedAtColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support Material download.
        /// </summary>
        public static string SupportMaterialDownloadToastrTitle {
            get {
                return ResourceManager.GetString("SupportMaterialDownloadToastrTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div&gt;&lt;h1&gt;Talk to us - Your Company Training&lt;/h1&gt;
        ///&lt;dl&gt;
        ///&lt;dt&gt;Name:&lt;/dt&gt;
        /// &lt;dd&gt;{name}&lt;/dd&gt;
        ///&lt;dt&gt;Email:&lt;/dt&gt;
        ///&lt;dd&gt;{email}&lt;/dd&gt;
        ///&lt;dt&gt;Message:&lt;/dt&gt;
        ///&lt;dd&gt;{message}&lt;/dd&gt;
        ///&lt;/dl&gt;
        ///&lt;/div&gt;.
        /// </summary>
        public static string TalkToUsEmailBody {
            get {
                return ResourceManager.GetString("TalkToUsEmailBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type your email.
        /// </summary>
        public static string TalkToUsEmailLabel {
            get {
                return ResourceManager.GetString("TalkToUsEmailLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Company Training - Talk to Us.
        /// </summary>
        public static string TalkToUsEmailSubject {
            get {
                return ResourceManager.GetString("TalkToUsEmailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has been ocurried. Please try again.
        /// </summary>
        public static string TalkToUsErrorMessage {
            get {
                return ResourceManager.GetString("TalkToUsErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Talk to us.
        /// </summary>
        public static string TalkToUsMenuItem {
            get {
                return ResourceManager.GetString("TalkToUsMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type your message here.
        /// </summary>
        public static string TalkToUsMessagePlaceholder {
            get {
                return ResourceManager.GetString("TalkToUsMessagePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your message has been sent!.
        /// </summary>
        public static string TalkToUsMessageSent {
            get {
                return ResourceManager.GetString("TalkToUsMessageSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type your name.
        /// </summary>
        public static string TalkToUsNameLabel {
            get {
                return ResourceManager.GetString("TalkToUsNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Talk to us.
        /// </summary>
        public static string TalkToUsTitle {
            get {
                return ResourceManager.GetString("TalkToUsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Talk to us.
        /// </summary>
        public static string TalkToUsToastrTitle {
            get {
                return ResourceManager.GetString("TalkToUsToastrTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teacher added.
        /// </summary>
        public static string TeacherAddedToastrMessage {
            get {
                return ResourceManager.GetString("TeacherAddedToastrMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teachers.
        /// </summary>
        public static string TeacherAdminMenuItem {
            get {
                return ResourceManager.GetString("TeacherAdminMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This teacher has classes associated to him.
        /// </summary>
        public static string TeacherClassesAssociationException {
            get {
                return ResourceManager.GetString("TeacherClassesAssociationException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teacher deleted!.
        /// </summary>
        public static string TeacherDeletedToastrMessage {
            get {
                return ResourceManager.GetString("TeacherDeletedToastrMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string TeacherEmailFieldName {
            get {
                return ResourceManager.GetString("TeacherEmailFieldName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This teacher is in charge of some courses.
        /// </summary>
        public static string TeacherInChargeException {
            get {
                return ResourceManager.GetString("TeacherInChargeException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teacher in charge.
        /// </summary>
        public static string TeacherInChargeTitle {
            get {
                return ResourceManager.GetString("TeacherInChargeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teacher management.
        /// </summary>
        public static string TeacherManagementPageTitle {
            get {
                return ResourceManager.GetString("TeacherManagementPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teacher management.
        /// </summary>
        public static string TeacherManagementToastrTitle {
            get {
                return ResourceManager.GetString("TeacherManagementToastrTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teacher.
        /// </summary>
        public static string TeacherName {
            get {
                return ResourceManager.GetString("TeacherName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string TeacherNameFieldName {
            get {
                return ResourceManager.GetString("TeacherNameFieldName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teacher updated.
        /// </summary>
        public static string TeacherUpdatedToastrMessage {
            get {
                return ResourceManager.GetString("TeacherUpdatedToastrMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Teacher.
        /// </summary>
        public static string TeacherUpdatePageTitle {
            get {
                return ResourceManager.GetString("TeacherUpdatePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string UserNameFieldName {
            get {
                return ResourceManager.GetString("UserNameFieldName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name required.
        /// </summary>
        public static string UserNameRequired {
            get {
                return ResourceManager.GetString("UserNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password required.
        /// </summary>
        public static string UserPasswordRequired {
            get {
                return ResourceManager.GetString("UserPasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://static.wixstatic.com/media/1ea5ec_1bb281895ae941fcbe351ceb04b3227e~mv2.jpg/v1/fill/w_1903,h_937,al_c,q_85,usm_0.66_1.00_0.01/1ea5ec_1bb281895ae941fcbe351ceb04b3227e~mv2.webp|https://static.wixstatic.com/media/1ea5ec_395870f78674481a8f37bc5320920a03~mv2.jpg/v1/fill/w_1903,h_937,al_c,q_85,usm_0.66_1.00_0.01/1ea5ec_395870f78674481a8f37bc5320920a03~mv2.webp|https://static.wixstatic.com/media/1ea5ec_f2bf38a61622476e982b80f75ce556c2~mv2.jpg/v1/fill/w_1903,h_937,al_c,q_85,usm_0.66_1.00_0.01/1ea5ec_f2bf38a6 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Wallpaper {
            get {
                return ResourceManager.GetString("Wallpaper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string WarningToastrTitle {
            get {
                return ResourceManager.GetString("WarningToastrTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last watched classes.
        /// </summary>
        public static string WatchedClassesTitle {
            get {
                return ResourceManager.GetString("WatchedClassesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to Your Company Training! Have a productive study!.
        /// </summary>
        public static string WelcomeNoticeMessage {
            get {
                return ResourceManager.GetString("WelcomeNoticeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have permission to download this material.
        /// </summary>
        public static string WithoutPermissionDownloadToastrMessage {
            get {
                return ResourceManager.GetString("WithoutPermissionDownloadToastrMessage", resourceCulture);
            }
        }
    }
}
