//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartLMS.Domain.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SmartLMS.Domain.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to index.
        /// </summary>
        public static string BackToIndex {
            get {
                return ResourceManager.GetString("BackToIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class created.
        /// </summary>
        public static string ClassCreatedToastrMessage {
            get {
                return ResourceManager.GetString("ClassCreatedToastrMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class Index.
        /// </summary>
        public static string ClassIndex {
            get {
                return ResourceManager.GetString("ClassIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class.
        /// </summary>
        public static string ClassName {
            get {
                return ResourceManager.GetString("ClassName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classes.
        /// </summary>
        public static string ClassPlural {
            get {
                return ResourceManager.GetString("ClassPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classroom management.
        /// </summary>
        public static string ClassroomManagementToastrTitle {
            get {
                return ResourceManager.GetString("ClassroomManagementToastrTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classroom updated.
        /// </summary>
        public static string ClassroomUpdatedToastrMessage {
            get {
                return ResourceManager.GetString("ClassroomUpdatedToastrMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content management.
        /// </summary>
        public static string ContentManagementToastrTitle {
            get {
                return ResourceManager.GetString("ContentManagementToastrTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Course Index.
        /// </summary>
        public static string CourseIndex {
            get {
                return ResourceManager.GetString("CourseIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Course.
        /// </summary>
        public static string CourseName {
            get {
                return ResourceManager.GetString("CourseName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This course is not available at this moment.
        /// </summary>
        public static string CourseNotAvailableToastrMessage {
            get {
                return ResourceManager.GetString("CourseNotAvailableToastrMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Courses.
        /// </summary>
        public static string CoursePlural {
            get {
                return ResourceManager.GetString("CoursePlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support Material.
        /// </summary>
        public static string FileName {
            get {
                return ResourceManager.GetString("FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Knowledge Area Index.
        /// </summary>
        public static string KnowledgeAreaIndex {
            get {
                return ResourceManager.GetString("KnowledgeAreaIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Knowledge Area.
        /// </summary>
        public static string KnowledgeAreaName {
            get {
                return ResourceManager.GetString("KnowledgeAreaName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Knowledge Areas.
        /// </summary>
        public static string KnowledgeAreaPlural {
            get {
                return ResourceManager.GetString("KnowledgeAreaPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New classes.
        /// </summary>
        public static string LastClassesTitle {
            get {
                return ResourceManager.GetString("LastClassesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Courses.
        /// </summary>
        public static string MyCoursesTitle {
            get {
                return ResourceManager.GetString("MyCoursesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We don&apos;t have any content in this section yet.
        /// </summary>
        public static string NoCourses {
            get {
                return ResourceManager.GetString("NoCourses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not allowed to watch this class.
        /// </summary>
        public static string NotAllowedWatchClassToastrMessage {
            get {
                return ResourceManager.GetString("NotAllowedWatchClassToastrMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification.
        /// </summary>
        public static string NotificationToastrTitle {
            get {
                return ResourceManager.GetString("NotificationToastrTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password updated!.
        /// </summary>
        public static string PasswordUpdatedToastrMessage {
            get {
                return ResourceManager.GetString("PasswordUpdatedToastrMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See also other classes for this course.
        /// </summary>
        public static string SeeOtherClasses {
            get {
                return ResourceManager.GetString("SeeOtherClasses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See also other courses for this subject.
        /// </summary>
        public static string SeeOtherCourses {
            get {
                return ResourceManager.GetString("SeeOtherCourses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See also other knowledge areas.
        /// </summary>
        public static string SeeOtherKnowledgeAreas {
            get {
                return ResourceManager.GetString("SeeOtherKnowledgeAreas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See also other subjects for this knowledge area.
        /// </summary>
        public static string SeeOtherSubjects {
            get {
                return ResourceManager.GetString("SeeOtherSubjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a class.
        /// </summary>
        public static string SelectClass {
            get {
                return ResourceManager.GetString("SelectClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a course.
        /// </summary>
        public static string SelectCourse {
            get {
                return ResourceManager.GetString("SelectCourse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a knowledge area.
        /// </summary>
        public static string SelectKnowledgeArea {
            get {
                return ResourceManager.GetString("SelectKnowledgeArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select below one of the classes available in this course.
        /// </summary>
        public static string SelectOneCourseIndexMessage {
            get {
                return ResourceManager.GetString("SelectOneCourseIndexMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select below one of the courses available in this subject.
        /// </summary>
        public static string SelectOneSubjectIndexMessage {
            get {
                return ResourceManager.GetString("SelectOneSubjectIndexMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a subject.
        /// </summary>
        public static string SelectSubject {
            get {
                return ResourceManager.GetString("SelectSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject Index.
        /// </summary>
        public static string SubjectIndex {
            get {
                return ResourceManager.GetString("SubjectIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject.
        /// </summary>
        public static string SubjectName {
            get {
                return ResourceManager.GetString("SubjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subjects.
        /// </summary>
        public static string SubjectPlural {
            get {
                return ResourceManager.GetString("SubjectPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support material download.
        /// </summary>
        public static string SupportMaterialDownloadToastrTitle {
            get {
                return ResourceManager.GetString("SupportMaterialDownloadToastrTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teacher added.
        /// </summary>
        public static string TeacherAddedToastrMessage {
            get {
                return ResourceManager.GetString("TeacherAddedToastrMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teacher management.
        /// </summary>
        public static string TeacherManagementToasterTitle {
            get {
                return ResourceManager.GetString("TeacherManagementToasterTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teacher updated.
        /// </summary>
        public static string TeacherUpdatedToastrMessage {
            get {
                return ResourceManager.GetString("TeacherUpdatedToastrMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string WarningToastrTitle {
            get {
                return ResourceManager.GetString("WarningToastrTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last watched classes.
        /// </summary>
        public static string WatchedClassesTitle {
            get {
                return ResourceManager.GetString("WatchedClassesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have permission to download this material.
        /// </summary>
        public static string WithoutPermissionDownloadToastrMessage {
            get {
                return ResourceManager.GetString("WithoutPermissionDownloadToastrMessage", resourceCulture);
            }
        }
    }
}
